### ISSUE TITLE
Package gives error of missing meta files

### ISSUE THREAD

**Issue by MostHated** [handzlikchris/Unity.MissingUnityEvents#2]
Hey there,
    I added this package yesterday to check it out, but when adding the package to the manifest the folder is immutable and it is missing the License meta file, so on every compilation, I receive this error:

    Asset Packages/missingunityevents/LICENSE has no meta file, but it's in an immutable folder. The asset will be ignored.

While functionally it doesn't do anything, I work hard to maintain clean output, so it is quite annoying to constantly get this in the logs.

![](https://i.imgur.com/kTFkyGW.png)

Thanks,
-MH

**Comment by handzlikchris** [comment]
Thanks for that, this will be github 'License' file - I'll look to get that sorted with some other features. Don't have any time for that to be honest, might be easiest to fix and make a pull request.

**Comment by handzlikchris** [comment]
That's now resolved, meta file submitted
