### ISSUE TITLE
[Recommendation] MenuItem location customization

### ISSUE THREAD

**Issue by MostHated** [handzlikchris/Unity.MissingUnityEvents#3]
Hey there,  
    This is more personal preference, but I am not a fan of individual items being placed into top-level menu items, especially when they cannot be changed, so I would like to recommend not creating a new top-level menu item for Missing Unity Events. I tend to be somewhat particular in how I organize things, and since installing things through the package manager makes the package immutable it adds an extra layer of unnecessary complexity in trying to change it to better suit my preferences. 

 I am not 100% on this, but I believe that a package can have its contents within the typical package structure/hierarchy, but also include files within the Assets folder. If this is the case, perhaps within the Assets/Editor folder could be a file that contains the [MenuItem("Missing Unity Events")] attributes and then they call back into the package, so that they are more easily customizable after importing the package?

Thanks,
-MH

**Comment by handzlikchris** [comment]
Hi @MostHated - thanks for getting in touch.

You make good point, I'll get it sorted when working on some other features, not quite sure when that'll happen though.

In the mean time in case if you'll adjust that yourself I'd be happy to merge that as a pull request.

Thanks,
Chris

**Comment by MostHated** [comment]
I am out of town at the current moment, but I can look into it whenever I get back and settled and see if I can come up with something.

**Comment by handzlikchris** [comment]
No customisation addded but menu items will go to tools submenu
