### ISSUE TITLE
Can't Modify CoreModule DLL

### ISSUE THREAD

**Issue by jrstrecker7852** [handzlikchris/Unity.MissingUnityEvents#6]
When clicking on the Weave Events to DLL i get an error that the file (DLL) can not be changed because an application has it open or need admin rights.  I tried opening Unity as Admin but that did not work.  Not sure how unless it my Unity session that the DLL would be being used.

![CoreModuleDllError](https://user-images.githubusercontent.com/69122922/116789122-e468d000-aa72-11eb-8cc3-a165c1802acf.PNG)
Any Ideas?

jrstrecker7852@gmail.com

**Comment by handzlikchris** [comment]
Hi, are you sure all Editor instances are closed when you click 'y'?

The tool specifies runas admin when it launches command-prompt so it should not matter that you're Unity is not run as admin.

If that doesn't work for any reason you can put a breakpoint in `EventILWeaverCommandLineArgsGenerator.GenerateAddEventsCommandLineArgs` - that'll give you an actual command that is run in the prompt. From there you can run cmd as admin and paste the command.

Hope that helps,
Chris

**Comment by jrstrecker7852** [comment]
Chris,

Thanks for getting back to me on this.  I will try your suggestions and let you know what if one of those works. 

Thanks again 
Jim

**Comment by jrstrecker7852** [comment]
I tried again making sure not Unity  Instances were open and still received
the error.  I was able to capture the command arguments and ran this
application in a cmd file.  This seems to work (created the new DLL, but I
did get the below error;

[image: image.png]

**Comment by handzlikchris** [comment]
That image wasn't attached. What are you getting?

**Comment by handzlikchris** [comment]
btw long path issue should be resolved now with latest push

**Comment by jrstrecker7852** [comment]
Chris,

The error was an 'InvalidOperationException: Sequence contains no matching
element.

**Comment by handzlikchris** [comment]
Could be that the field you're tring to add was not found. Not sure - probably you're best bet is to pull
https://github.com/handzlikchris/AddingEventsToCompiled3rdPartyLibrary
And run that command with debugger attached. That'll give you some more info

**Comment by jrstrecker7852** [comment]
I wasn’t adding anything at this time, but I’ll look into your suggestion. 

Thanks

**Comment by handzlikchris** [comment]
ahh that could be why you're getting this error - maybe it's not handing empty well

**Comment by handzlikchris** [comment]
I'll get this one closed, please get in touch if you need more help. thanks
