### ISSUE TITLE
VirusTotal check gives positive results

### ISSUE THREAD

**Issue by NeistH2o** [handzlikchris/Unity.MissingUnityEvents#9]
I just verified EventILWeaver.Console.exe with VirusTotal as I always do with downloaded executables, I expected some positive results as it's about DLL modifications, but one of them says "Trojan" so I wanted to point it out.

https://www.virustotal.com/gui/file/797920c046ac80c1d4c115b55a0e04d6b70bbe9a4952188be88f7270aac072b1

![image](https://user-images.githubusercontent.com/25915415/142747082-e3ef7dd6-e14f-46a6-a23b-b30b459f834f.png)

**Comment by handzlikchris** [comment]
Thanks, as you mentioned this will be down to DLL modification. Nothing to worry about.

The source code for that exe is available from
https://github.com/handzlikchris/AddingEventsToCompiled3rdPartyLibrary

you can compile that version directly and use instead
